package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.87

import (
	"context"
	"fmt"
	"os"
	"encoding/json"
	"github.com/riuchek/api/graph/model"
)

// CreateStory is the resolver for the createStory field.
func (r *mutationResolver) CreateStory(ctx context.Context, input model.NewStory) (*model.Story, error) {
	panic(fmt.Errorf("not implemented: CreateStory - createStory"))
}

// Stories is the resolver for the stories field.
func (r *queryResolver) Stories(ctx context.Context) ([]*model.Story, error) {
	panic(fmt.Errorf("not implemented: Stories - stories"))
}

// TestStories is the resolver for the testStories field.
func (r *queryResolver) TestStories(ctx context.Context) ([]*model.Story, error) {
	content, _ := os.ReadFile("data/test_stories.json")
	var stories []*model.Story
	json.Unmarshal(content, &stories)
	return stories, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
