type User {
  id: ID!
  username: String!
  email: String!
}

type AuthPayload {
  token: String!
  user: User!
}

input RegisterInput {
  username: String!
  email: String!
  password: String!
}

input LoginInput {
  email: String!
  password: String!
}

input UpdateWorldInput {
  name: String
  description: String
}

type World {
  id: ID!
  name: String!
  description: String
}

type Backstory {
  id: ID!
  title: String!
  characterName: String!
  content: String!
  world: World!
}

type Query {
  me: User
  myWorlds: [World!]!
  world(id: ID!): World
  backstories(worldId: ID!): [Backstory!]!
}

type Mutation {
  register(input: RegisterInput!): AuthPayload!
  login(input: LoginInput!): AuthPayload!
  createWorld(name: String!, description: String): World!
  updateWorld(id: ID!, input: UpdateWorldInput!): World!
  deleteWorld(id: ID!): Boolean!
  saveBackstory(title: String!, content: String!, worldId: ID!): Backstory!
}