// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Mutation struct {
}

type NewStory struct {
	Title   string `json:"title"`
	Content string `json:"content"`
	Year    int32  `json:"year"`
}

type Query struct {
}

type Story struct {
	ID      string `json:"id"`
	Title   string `json:"title"`
	Content string `json:"content"`
	Year    int32  `json:"year"`
}
